### ISSUE TITLE
Expo Support : Can I easily convert this to an Expo project?

### ISSUE THREAD

**Issue by jd-alexander** [osamaq/react-native-template#2]
Hi! 
Thanks for this great template. I am wondering if it can be used with the Expo.io platform as I am considering it as a starting point for my project. Please let me know.

**Comment by osamaqarem** [comment]
Hi there. I'm sorry but no. This template only works with the react-native cli.

The typescript template from expo is a good alternative starting point though! 
https://docs.expo.io/guides/typescript/

I believe the following libraries in this template do not support the Expo managed workflow:

- Sentry SDK
- Detox
- react-native-config (expo managed projects do not need this as the native code is abstracted away)
- react-native-bootsplash (expo managed  projects do not need this as they already have a SplashScreen module)

If your project uses the expo bare workflow (same as when ejecting I believe) you could install the libraries from this template onto your project, and then copy over the files. This is not "easy" as you were asking, but just letting you know 👍

Hope this helps.

**Comment by jd-alexander** [comment]
Understood. Thanks, much @osamaq I am still going to use this template nonetheless. I appreciate all the work you put into it.
